AWSTemplateFormatVersion: '2010-09-09'
Description: Pila del servidor para la base de datos

Parameters:

  InstanceType:
    Description: Parametro para seleccionar el tipo de instancia EC2
    Type: String
    Default: t2.small
    AllowedValues:
      - t2.large
      - t2.medium
      - t2.small
      - t2.micro
      - t2.nano

  InstanceImage:
    Description: Parametro para seleccionar la AMI Ubuntu 22.04
    Type: String
    Default: "ami-0f9de6e2d2f067fca"
  
  InstanceKeyName:
    Description: Parametro para seleccionar el KeyName de la Instancia
    Type: String
    Default: "vockey"
  
  HostedZoneName:
    Type: String
    Description: Nombre del dominio para la zona hospedada en Route 53
    Default: "chefmate"

Resources:

  DatabaseDNS:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneId:
        Fn::ImportValue: "HostedZone"
          
      RecordSets:
        - Name: !Sub "db.${HostedZoneName}."
          Type: A
          TTL: '900'
          ResourceRecords:
            - !GetAtt Database.PrivateIp

  Database:
    Type: "AWS::EC2::Instance"
    Description: Servidor de la BBDD
    Properties:
      Tags:
        - Key: "Name"
          Value: "db"
      ImageId: !Ref InstanceImage
      InstanceType: !Ref InstanceType 
      KeyName: !Ref InstanceKeyName
      SecurityGroupIds: 
        - Fn::ImportValue:
            !Sub "db-sg"
        - Fn::ImportValue:
            !Sub "ssh-sg"
      UserData: 
        Fn::Base64: !Sub |
          #!/bin/bash
          exec > /tmp/userdata.log 2>&1   

          #====================================================================#
          #----------------------> PREPARAR SERVIDOR <-------------------------#
          #====================================================================#

          # Actualizar la lista de paquetes de la instancia
          apt update 
          apt upgrade -y

          # Instalar docker y habilitarlo
          apt-get install  curl apt-transport-https ca-certificates software-properties-common -y
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
          add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
          apt update 
          apt install docker-ce -y
          systemctl enable docker
          systemctl start docker

          # Crear directorio para la base de datos
          mkdir -p /home/ubuntu/mysql
          chown ubuntu:ubuntu /home/ubuntu/mysql

          #====================================================================#
          #----------------------> LANZAR CONTENEDOR <-------------------------#
          #====================================================================#
          
          docker run -d \
            --name mysql-db \
            -e MYSQL_ROOT_PASSWORD=chefmate_password \
            -e MYSQL_DATABASE=chefmate \
            -e MYSQL_USER=chefmate_user \
            -e MYSQL_PASSWORD=chefmate_password \
            -v /home/ubuntu/mysql:/var/lib/mysql \
            -p 3306:3306 \
            --restart unless-stopped \
            mysql:8
Outputs:

  Database:
    Value: !GetAtt Database.PrivateIp
    Export:
      Name: db