AWSTemplateFormatVersion: '2010-09-09'
Description: Pila del servidor para la langing-page

Parameters:

  InstanceType:
    Description: Parametro para seleccionar el tipo de instancia EC2
    Type: String
    Default: t2.small
    AllowedValues:
      - t2.large
      - t2.medium
      - t2.small
      - t2.micro
      - t2.nano

  InstanceImage:
    Description: Parametro para seleccionar la AMI Ubuntu 22.04
    Type: String
    Default: "ami-0f9de6e2d2f067fca"
  
  InstanceKeyName:
    Description: Parametro para seleccionar el KeyName de la Instancia
    Type: String
    Default: "vockey"
  
  HostedZoneName:
    Type: String
    Description: Nombre del dominio para la zona hospedada en Route 53
    Default: "chefmate"


Resources:

  LandingDNS:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneId:
        Fn::ImportValue: "HostedZone"
          
      RecordSets:
        - Name: !Sub "landing.${HostedZoneName}."
          Type: A
          TTL: '900'
          ResourceRecords:
            - !GetAtt Landing.PrivateIp
  
  LandingIP:
    Type: AWS::EC2::EIP

  Landing:
    Type: "AWS::EC2::Instance"
    Description: Servidor de la landing-page
    Properties:
      Tags:
        - Key: "Name"
          Value: "landing"
      ImageId: !Ref InstanceImage
      InstanceType: !Ref InstanceType 
      KeyName: !Ref InstanceKeyName
      SecurityGroupIds: 
        - Fn::ImportValue:
            !Sub "http-sg"
        - Fn::ImportValue:
            !Sub "https-sg"
        - Fn::ImportValue:
            !Sub "ssh-sg"
      UserData: 
        Fn::Base64: !Sub |
          #!/bin/bash
          exec > /tmp/userdata.log 2>&1

          #====================================================================#
          #----------------------> PREPARAR SERVIDOR <-------------------------#
          #====================================================================#

          # Actualizar la lista de paquetes de la instancia
          apt update 
          apt upgrade -y

          # Instalar apache, git y curl
          apt install -y apache2 git unzip curl

          # Clonar repositorio de ChefMate
          cd /home/ubuntu
          git clone https://@github.com/FranciscoCabelloRueda/Chefmate.git chefmate
          chown -R ubuntu:ubuntu /home/ubuntu/chefmate
          
          #====================================================================#
          #---------------------> MONTAR LANDING-PAGE <------------------------#
          #====================================================================#

          # Eliminamos todos los archivos del directorio raiz de apache y montamos la landing-page
          rm -rf /var/www/html/*
          cp -r /home/ubuntu/chefmate/landing-page/* /var/www/html/
          chown -R www-data:www-data /var/www/html
          chmod -R 755 /var/www/html

          # Habilitamos y reiniciamos apache
          systemctl enable apache2
          systemctl restart apache2
  
  LandingAssociation:
    Type: AWS::EC2::EIPAssociation
    Properties:
      InstanceId: !Ref Landing
      EIP: !Ref LandingIP

Outputs:

  Landing:
    Value: !GetAtt Landing.PrivateIp
    Export:
      Name: landing